baseURL = "https://0xNF.github.io"
title = "0xNF, yo"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "0xNF's pages, dawg"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "MunifTanjim"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Minimo"

[author.social]
  codepen = "MunifTanjim"
  email = "contact@example.com"
  facebook = "MunifTanjim"
  github = "MunifTanjim/minimo"
  instagram = "instagram"
  twitter = "MunifTanjim"
  linkedin = "muniftanjim"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Repo"
  weight = -70
  identifier = "0xNF"
  url = "https://0xNF.github.io"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
