baseURL = "https://0xnf.github.io/"
languageCode = "en-us"
title = "Nothing in Particular"
theme = "anatole"
pygmentsCodeFences = true
linenos = true
[taxonomies]
 tag = "tags"
 category = "categories"
 series = "series"

 [module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false