baseURL = "https://0xnf.github.io/"
languageCode = "en-us"
title = "Nothing in Particular"
theme = "anatole"
pygmentsCodeFences = true
linenos = true
[taxonomies]
 tag = "tags"
 category = "categories"
 series = "series"